### ISSUE TITLE
Bias in the Classifier Class

### ISSUE THREAD

**Issue by cpphoo** [gidariss/FewShotWithoutForgetting#24]
First off, thanks for sharing your code!
I was looking at the Classifier class in ClassifierWithFewShotGenerationModule.py and I realized that self.bias is a scalar rather than a vector. In the simple dot product classifier (or linear classifier), the bias should be a vector with size equal to the number of classes. Am I missing something or is this a bug in the code?

**Comment by gidariss** [comment]
Hi,

I don't use a bias or I might use the same bias for all the classes (which is the same as not using bias). This way I avoid biasing the base classes over the novel classes or the other way around.
Spyros
