### ISSUE TITLE
link to the dataset is invalid

### ISSUE THREAD

**Issue by kailigo** [gidariss/FewShotWithoutForgetting#5]
Hi, the link to the mini-imagenet dataset is invalid now. Could you hep check it and update the link. thanks.

**Comment by gidariss** [comment]
Hi, I just checked the link and it is working fine. Are you sure that you are having problems.

Link:
https://mega.nz/#!rx0wGQyS!96sFlAr6yyv-9QQPCm5OBFbOm4XSD0t-HlmGaT5GaiE

**Comment by kailigo** [comment]
The firewall blocks this site. After switching to another network, it works fine. Thanks.
