### ISSUE TITLE
Installation Requirements

### ISSUE THREAD

**Issue by Supersak80** [gidariss/FewShotWithoutForgetting#8]
Hi, @gidariss could you please list the installation requirements/dependencies to run your code? i.e., python 2.X/3.X, pytorch 0.X, other packages, etc?

**Comment by gidariss** [comment]
The code is developed and tested with pytorch version 0.2.0_4.
I also used the packages, torchnet, tqdm, h5py, and obviously numpy.

**Comment by Supersak80** [comment]
Thank you!
